# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "ZazuPay"
description: > # this means to ignore newlines until "email:"
   Africa’s first digital only bank.

email: hello@ilovezazu.com
#blog logo
logo: "/assets/images/zazu.jpg"
headerLogo: "/blog/assets/images/zazu.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/benefits.jpg"

name: 'ZazuPay'
author: 'ZazuPay'
author_image: "/assets/images/zazu.jpg"

paginate:	5

url: "blog.ilovezazu.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@ilovezazu'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/ilovezazu
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="


#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
